### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by ghoneycutt** [puppet-community/puppet-module-puppetboard#78]
Hi, 

Features have been added to master but without a corresponding release. Could you please cut a new tag?

Thanks,
-g

**Comment by Jmeyering** [comment]
:100:  This would be much appreciated!

**Comment by nibalizer** [comment]
Okay I will do this on the train. Sorry folks!

**Comment by nibalizer** [comment]
I didn't do this on the train. Sorry. Writing changelogs is harder than it looks.

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-module-puppetboard/pull/82 check it

**Comment by nibalizer** [comment]
https://github.com/puppet-community/puppet-module-puppetboard/tree/2.7.2

**Comment by nibalizer** [comment]
In theory that should run some travis builds and we should have a new forge release momentarily.

**Comment by nibalizer** [comment]
I must set up the correct dotfiles so that auto-deployment works, which means I need to set up a modulesync configs repo which means it's probably not happening today. If anyone must have forge, can't have a git tag, ping me and either I'll have you help with the modulesync configs or I will upload to forge manually.

**Comment by igalic** [comment]
@nibalizer are we there yet ;)

**Comment by nibalizer** [comment]
I totally did this.
